### PR TITLE
Replaces npm with yarn

### PR DESCRIPTION
**Pull request by gijsstegehuis**

### CODE REVIEW

**Comment by boboldehampsink** [comment]
Doesn't yarn need a yarn.lock file?

**Comment by gijsstegehuis** [comment]
not necessarily + you would need to add `yarn.lock` to a `.slugignore` file in your project.
see: https://github.com/heroku/heroku-buildpack-nodejs/issues/337#issuecomment-267980492

**Comment by boboldehampsink** [comment]
Can't you check if there's a yarn.lock file, then execute yarn - else execute npm?

**Comment by gijsstegehuis** [comment]
Fixed in https://github.com/nerds-and-company/docker-heroku-php/pull/1/commits/272d93d5ac8beb214c5f947432b292e208cdba59

**Review by boboldehampsink — APPROVED** [review]

**Pull request merged**
